name: curious_traveler
description: AI-driven personalized city exploration app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  webview_flutter: ^4.2.2
  url_launcher: ^6.3.2
  provider: ^6.1.2
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  mockito: ^5.5.1
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  patrol: ^3.19.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21